
// Objective-C API for talking to the following Go packages
//
//	github.com/decentralised-dataexchange/presentation-exchange-sdk-ios/go/pexioswrapper
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pexioswrapper_FRAMEWORK_H__
#define __Pexioswrapper_FRAMEWORK_H__

#include "Pexioswrapper.objc.h"
#include "Universe.objc.h"

#endif
