// Objective-C API for talking to github.com/decentralised-dataexchange/presentation-exchange-sdk-ios/go/pexioswrapper Go package.
//   gobind -lang=objc github.com/decentralised-dataexchange/presentation-exchange-sdk-ios/go/pexioswrapper
//
// File is generated by gobind. Do not edit.

#ifndef __Pexioswrapper_H__
#define __Pexioswrapper_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull PexioswrapperMatchCredentials(NSString* _Nullable inputDescriptorJson, NSString* _Nullable credentials);

#endif
